# lightning.pytorch==2.4.0
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "PPG_VC_Matcha_AutoEncoder"
      name: 
      save_dir: "./logs/"
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: './exp'
        monitor: 'val/mel_loss'
        save_top_k: 5
        save_on_train_epoch_end: false
        auto_insert_metric_name: true
        mode: 'min'
        save_last: true
  fast_dev_run: false
  max_epochs: -1
  min_epochs: 20
  max_steps: 500000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 5
  enable_checkpointing: true
  enable_progress_bar: false
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  class_path: ppg_tts.tts.LightningModule.VQVAEMatchaVC
  init_args:
    pitch_stats: /scratch/elec/t412-speechsynth/DATA/fin-mix/train/stats.json
    ppg_dim: 34
    ppg_variance: 0.4897841937287568
    num_emb: 32
    encode_dim: 128
    spk_emb_size: 512
    spk_emb_enc_dim: 128
    pitch_emb_size: 16
    dropout: 0.1
    target_dim: 80
    decoder_num_mid_block: 2
    sigma_min: 1e-4
    lr: 1e-4
    gamma: 0.99
    no_ctc: false
    diff_steps: 10
    transformer_type: transformer
    temperature: 0.667
    ae_kernel_sizes: [3,3,1]
    ae_dilations: [2,4,8]
    first_stage_steps: 5000
    second_stage_steps: 5000
    lr_scheduler_interval: 1500
    n_trans_layers: 2
optimizer: null
lr_scheduler: null
ckpt_path: null
